### PR TITLE
ImagingPath's ray fan variables should not be used. They are deprecated.

### LINKED ISSUE #266: `ImagingPath` should use Rays() instead of object and fanAngle etc...
We have the right mechanism to create multiple rays of appropriate distribution.  We should use an instance of Rays() instead of separate variables in `ImagingPath`.

### PR DESCRIPTION
**Pull request by GabGabG**
**This is still a work on progress. I want to get your feedback on this before I dive too much in it**

Since we have classes such as `UniformRays`, `RandomRays`, etc, using `Ray` static methods `fan` and `fanGroup` is not really recommended anymore. Hence, we should not use multiple variables in `ImagingPath` (`fanAngle`, `fanNumber`, `rayNumber`).

I implemented properties getter / setter for those 3 attributes. With that, we don't change the API and it allows us to send warnings about the deprecation of them. It adds quite some code lines, but eventually in a future version we could simply remove the variables and remove said code lines. Current users are now warned that they should change their code because we will eventually remove `fanAngle`, `fanNumber`, `rayNumber`. I searched a bit on internet to know if there was a simpler way to add deprecation warnings to attributes, but I didn't find anything simpler.

I also created a new property, `rays`, which is a `UniforRays` instance. It is initialized in the constructor with default values and it can be updated with `updateRays` method. This method takes `yMax`, `yMin`, `thetaMax`, `thetaMin`, `M`, `N` to create new rays.

I did not test it before creating this <s>pull</s> review request. I also did not change anything related to demos that involves `fanAngle`, `fanNumber`, `rayNumber`. I want to know what you think before I modify too many lines.

Might fix #266

### CODE REVIEW

**Comment by GabGabG** [comment]
The code might not be as optimized as it can be. It is only a draft to show what's on my mind about issue #266

**Comment by dccote** [comment]
I am thinking a better option is to pass `Rays` to `display()`.  The `objectHeight` and others are never really used until the whole thing is displayed. It caused confusion to other users: `fieldOfView()`, `objectHeight`, which one is used?

I like the idea of completely removing this aspect that is *totally* display-related.

We could have:
```
display(self, rays=None)
   # if rays is None, use principalAndAxialRays with objectHeight = field of view

displayWithObject(self, height, fanAngle, fanNumber, rayNumber):
    # create Rays() and call self.display(rays)

```
or something like that to move the object and ray tracing "out" of the ImagingPath. Do you think it makes sense?

**Comment by GabGabG** [comment]
I like the idea to separate the display stuff from the intern computing stuff. I feel like it would be easier to maintain and easier to work with.

**Comment by dccote** [comment]
> I like the idea to separate the display stuff from the intern computing stuff. I feel like it would be easier to maintain and easier to work with.

Will you have time to do it? If not, I could give it a try.

**Comment by GabGabG** [comment]
> Will you have time to do it? If not, I could give it a try.

Isn't it what `figure.py` is supposed to do already? I thought the process of separating the computations from the display was already in motion. If not, I can work on that, no problem.

**Comment by dccote** [comment]
I made a mistake and started another branch.  I think this branch will become dated and redundant.

**Pull request closed without merging**
