### PR TITLE
Tests matrix group 98% coverage

### PR DESCRIPTION
**Pull request by GabGabG**
There are two functions not covered: `ImagingPath()` and `LaserPath()`. The fact that they are not tested is related to issue #90 . There is also one missing condition branch in `intermediateConjugates()`. It cannot be tested because the condition is `if distance is not None` and `distance` cannot be `None`. It can be infinity, **perhaps we should check if the conjugate is at infinity?**

### CODE REVIEW

**Comment by dccote** [comment]
I am wondering if we should return a conjugateMatrix with +inf elements? Technically, it does exist as a limit. I wonder how well the rest of functions would behave?

**Comment by dccote** [comment]
I added tests for limits to see if we could keep +inf and -inf as values.  I am still not sure, but we can certainly handle well defined limits (inf * inf for instance), this is one automatically. I think the problem we will have is with inf * 0, which will happen.  I am looking into that.

**Comment by GabGabG** [comment]
> I think the problem we will have is with inf * 0, which will happen. I am looking into that.
Yes, in python, inf * 0 is nan, this is kind of weird that this indetermination is considered, but 1^inf and inf^inf is not.

**Comment by dccote** [comment]
> > I think the problem we will have is with inf * 0, which will happen. I am looking into that.
> 
> Yes, in python, inf * 0 is nan, this is kind of weird that this indetermination is considered, but 1^inf and inf^inf is not.


Interesting for 1^inf, but not surprising: 1.0 is exact in binary, so it simply handles it directly I guess with (1)^anything always returns 1.  Wouldn't be so nice if 1.0 was in fact 1.00000001 or 0.9999999.  As a result of calculation, this would go one way or the other.

**Pull request merged**
