### PR TITLE
Display of compound lens

### PR DESCRIPTION
**Pull request by JLBegin**
*Currently a draft until we make a decision about the fact that this PR requires some commits from the branch grinLenses. 

The file lensBuilder.py can now display the elements from prescription file using the CompoundLens class. 

- Added default forward surfaces in CompoundLens. 
- Added diameter argument to CompoundLens in order to correctly set apertureDiameter (default to infinity).

@dccote is this the figure you were expecting ?

image

### Limitations
- When trying to display the resulting CompoundLens inside an imaging path, it raises an error about the system matrix being ill-defined. 
- The resulting surface graphic is a bit off in the corners. See image:
Screen Shot 2022-05-20 at 3 54 32 PM

### CODE REVIEW

**Comment by dccote** [comment]
This is not bad at all actually.

**Comment by dccote** [comment]
How do I get the same printout that you have above? The multi-element display? Give me some code to test it please.

**Comment by JLBegin** [comment]
I run the prescription script at `raytracing/specifications/lensBuilder.py`.

**Comment by dccote** [comment]
To fix a bug introduced in the grinLens branch, a few commits from this branch were copied and the branch was closed.

**Pull request closed without merging**
