### PR TITLE
try the change relative paths to RAW html links

### PR DESCRIPTION
**Pull request by PyMarc2**
Seems to be the consensus online as the main fix to the relative path or blob link problems

### CODE REVIEW

**Comment by dccote** [comment]
I believe this was fixed, but only in tutorial branch.... Sorry.

**Comment by dccote** [comment]
Was already solved but not noted as such.  My bad.

**Comment by dccote** [comment]
it is not a solved issue.

**Comment by dccote** [comment]
@pymarc2 Where do we stand with thIs? Do we need REadme.rst? How is it maintained?

**Comment by dccote** [comment]
@PyMarc2 Where do we stand on this?

**Comment by PyMarc2** [comment]
The .rst can be made automatic, but it isn't for now. but from what I'm reading, it isn't the problem. I've seen packages with .md with their images working. e.g tensorflow, tensorflow scientific. I'm really not sure yet, there's no pattern

**Comment by PyMarc2** [comment]
Resolved (the problem works with the RAW links, it's just Pypi that takes time to update)

**Pull request closed without merging**
