### PR TITLE
issue#120_testsSpecialtyLenses merge with Master

### PR DESCRIPTION
**Pull request by MFournierQC**

### CODE REVIEW

**Comment by MFournierQC** [comment]
drawAt and drawAperture were not tested since they are hard to tests and changes were coming. All subclasses of AchromatDoubletLens and Objective should be tested as well as most functions of the mentioned classes however.

There are a lot of UserWarnings that I didn't feel comfortable touching.

Also the FutureWarning of Objective might possibly be deleted at this point?

**Comment by MFournierQC** [comment]
There were some mistakes in the Achromatic Doublet Lenses of Thorlabs that I corrected but I still get some `UserWarning` ;

```python
UserWarning:Doublet AC254-030-A: Obtained back focal length 22.23 is not within 1% of expected 22.9
UserWarning:Doublet AC254-125-A: obtained thickness 5.3 does not match expected 5.0
```

For the LA####_A, I'm a bit confused. These are plano-convex lenses but they are handled as achromatic doublet lenses. Wouldn't there be a better way to handle these?

Either way, I checked for the LA1608_A lens and we have something like this ;

```python
super(LA1608_A,self).__init__(fa=75.0,fb=72.0, R1=100000,R2=-100000, R3=-38.6,
                                    tc1=.05, tc2=4.1, te=2.0, n1 = 1, n2=N_BK7.n(0.5876), diameter=25.4,
                                    url='https://www.thorlabs.com/thorproduct.cfm?partnumber=LA1608-A',
                                    label="LA1608_A")
```
Since it's a Plano-convex lens, shouldn't R1=38.6 and R3=(+/-)100000? If I make the change, the warning does vanish. However, we are left with a `UserWarning` for the thickness of the lens ;

```python
UserWarning:Doublet LA1608_A: obtained thickness 4.1 does not match expected 2.0
```

Also, it would seem the same 'mistake' has been made for most of the LA####_A lenses. I'd like your input for these. Meanwhile, I'm checking for the Edmund Optics lenses.

**Comment by MFournierQC** [comment]
I've been looking at the `PN_33_922` because I get the following errors ;

```python
UserWarning:Doublet EO #33-922: Obtained effective focal length 135.0 is not within 1% of expected 150.0

UserWarning:Doublet EO #33-922: Obtained back focal length 112.7 is not within 1% of expected 126.5
```
And I seriously cannot find what's wrong. The `EO #33-922` is given by ;

```python
class PN_33_922(AchromatDoubletLens):
    def __init__(self):
        # PN for Part number
        super(PN_33_922,self).__init__(fa=150.00,fb=126.46, R1=92.05,R2=-72.85, R3=-305.87, 
                                    tc1=23.2, tc2=23.1, te=36.01, n1=1.6700, n2=1.8467, diameter=75,
                                    label="EO #33-922",
                                    url="https://www.edmundoptics.com/p/75mm-dia-x-150mm-fl-vis-0-coated-achromatic-lens/3376/")
```
I went on their website and the variables seem to be correct. I checked the UserWarning part of the code ;
```python
# After having built the lens, we confirm that the expected effective
# focal length (fa) is actually within 1% of the calculated focal length
(f, f) = self.focalDistances()
if abs((f - fa) / fa) > 0.01:
     msg = "Doublet {2}: Obtained effective focal length {0:.4} is not within 1% of " \
                "expected {1:.4}".format(f, fa, self.label)
     warnings.warn(msg, UserWarning)
BFL = self.backFocalLength()
if abs((BFL - fb) / fb) > 0.01:
     msg = "Doublet {2}: Obtained back focal length {0:.4} is not within 1% of " \
                 "expected {1:.4}".format(BFL, fb, self.label)
     warnings.warn(msg, UserWarning)
```
But I can't find anything wrong with. Also it seems to be working correctly with every other lenses but one, the `AC254-030-A` so I figure it has to be something else but I can't quite put my finger on it. `self.focalDistances()` is essentially `-1 / self.C` while `self.backFocalLength()` is ;
```python
(f1, f2) = self.effectiveFocalLengths()
(p1, p2) = self.principalPlanePositions(z=0)
return (p2 + f2 - self.backVertex)
```

**Comment by dccote** [comment]
> There were some mistakes in the Achromatic Doublet Lenses of Thorlabs that I corrected but I still get some `UserWarning` ;
> 
> ```python
> UserWarning:Doublet AC254-030-A: Obtained back focal length 22.23 is not within 1% of expected 22.9
> UserWarning:Doublet AC254-125-A: obtained thickness 5.3 does not match expected 5.0
> ```
> 
> For the LA####_A, I'm a bit confused. These are plano-convex lenses but they are handled as achromatic doublet lenses. Wouldn't there be a better way to handle these?
> 
> Either way, I checked for the LA1608_A lens and we have something like this ;
> 
> ```python
> super(LA1608_A,self).__init__(fa=75.0,fb=72.0, R1=100000,R2=-100000, R3=-38.6,
>                                     tc1=.05, tc2=4.1, te=2.0, n1 = 1, n2=N_BK7.n(0.5876), diameter=25.4,
>                                     url='https://www.thorlabs.com/thorproduct.cfm?partnumber=LA1608-A',
>                                     label="LA1608_A")
> ```
> 
> Since it's a Plano-convex lens, shouldn't R1=38.6 and R3=(+/-)100000? If I make the change, the warning does vanish. However, we are left with a `UserWarning` for the thickness of the lens ;
> 
> ```python
> UserWarning:Doublet LA1608_A: obtained thickness 4.1 does not match expected 2.0
> ```
> 
> Also, it would seem the same 'mistake' has been made for most of the LA####_A lenses. I'd like your input for these. Meanwhile, I'm checking for the Edmund Optics lenses.

Well, that explains it: I did not enter these lenses in the module, and they are not doublets, so they should be treated like singlets! I am not sure how it got treated as a Doublet, that will teach me to accept new lenses without tests.

Based on AchromatDoublet, create a class called Singlet with the necessary parameters (really, just use Doublets but with obviously only two radii, and one material). Put it in specialtyLenses too.

**Comment by MFournierQC** [comment]
I've made the changes and create a new branch and a new pull request specific for those.

Also I forgot to mention but `testsSpecialLenses.py` could most likely be deleted now since `testsSpecialtyLenses.py` does the same thing but better. I just wanted your input before I go deleting files.

**Pull request merged**
