### PR TITLE
New documentation platform

### PR DESCRIPTION
**Pull request by JLBegin**
Rebased pull request #100 

Available at https://raytracing.readthedocs.io/

- Using [Sphinx](https://www.sphinx-doc.org/en/master/) documentation generator. This is easily maintained with 
  - The configuration file `conf.py` (set theme, extensions, etc). 
  - The `index.rst` referring to the different sections of the docs (2 for now) : `reference.rst` (API autodocs) and `README.md`. 
  - The API docs are generated from `reference.rst` which calls a custom template for auto-class documentation `_templates\autoClass.rst`. 
- Hosted on [ReadTheDocs](https://readthedocs.org/) which also automates the building.

### Docstring Format
The API documentation is automatically generated from the docstrings in the code. The docstrings have to follow the required [Numpy Docstring](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html) format.

More info in the [README](https://github.com/DCC-Lab/RayTracing/blob/documentation/docs/README-documentation.md) 

### TODO
- Complete ray.py with the proper docstring format. 
- Complete the readme with more info about config and maintaining.
- ~~Create relevant sections for the documentation (they can be empty for now) like getting started, installation, api, examples, etc.~~

### CODE REVIEW

**Comment by dccote** [comment]
Please provide an exemple for `ray.py` so everyone can take a look as they work on the documentation.

**Comment by dccote** [comment]
@ElaheParham Discuss with Ludo, I will take care of the final merge into Master when this is approved.

**Comment by dccote** [comment]
Please make sure that the necessary steps to recreate/manage the documentation are well documented within each configuration file.
Please keep info in the files themselves and in the README-Documentation.md file.

**Comment by dccote** [comment]
On readthedocs, I don't like that the first thing is about Sphynx documentation.  Move Raytracing documentation first, and Sphynx can be removed I think.

**Comment by ElaheParham** [comment]
> @JLBegin On readthedocs, I don't like that the first thing is about Sphynx documentation. Move Raytracing documentation first, and the section about Sphynx can be removed I think on readthedocs.

That is the template. I am working on that (the contents of the page) and I will write a sample Numpy style guide for ray.py today.

**Comment by dccote** [comment]
> > @JLBegin On readthedocs, I don't like that the first thing is about Sphynx documentation. Move Raytracing documentation first, and the section about Sphynx can be removed I think on readthedocs.
> 
> That is the template. I am working on that (the contents of the page) and I will write a sample Numpy style guide for ray.py today.

I did a bit of work work `Ray` today.  When you update you will see that.

**Comment by JLBegin** [comment]
I think we still need to complete the ray.py docstrings with examples and possibly exceptions and notes so it's a better reference developers.

**Pull request merged**
