### PR TITLE
Achromats take wavelenght argument and corrects focal for used wavelenght

### PR DESCRIPTION
**Pull request by PyMarc2**
- Achromat wavelenght correction
- All thorlabs lenses take wavelenght argument
- test of focal shift with wavelenght argument

### CODE REVIEW

**Comment by PyMarc2** [comment]
will look at the merge conflicts

**Comment by dccote** [comment]
There were many typos in the code.  Running the tests would have shown them to you quickly.  Make sure you run `python -m unittest`.  In particular her, run `python testsSpecialtyLenses.py`.

That said, I fixed many, but there remains a few bugs. By running `python testsSpecialtyLenses.py` you will see them.

**Comment by PyMarc2** [comment]
Yes! You shouldn't repair them! I'd really like Elodie and Charles Eric to commit the repairs and make the tests if necessary. I've shown them how to do everything they should be 99% capable of doing it with 1% help

**Comment by dccote** [comment]
> Yes! You shouldn't repair them! I'd really like Elodie and Charles Eric to commit the repairs and make the tests if necessary. I've shown them how to do everything they should be 99% capable of doing it with 1% help.

Done.  Simple tops in base classes.

**Comment by PyMarc2** [comment]
> > Yes! You shouldn't repair them! I'd really like Elodie and Charles Eric to commit the repairs and make the tests if necessary. I've shown them how to do everything they should be 99% capable of doing it with 1% help.
> 
> Done. Simple typos in base classes.
> 
> Testing, testing, testing: this type of refactor is a perfect example case for tests. Our tests caught all the typos.

Amazing!

**Pull request merged**
